# -*- coding: utf-8 -*-
"""Resume_Screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199gFFmHLcuLFkzkLnb7UQoVPuqM0SqMS
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("UpdatedResumeDataSet.csv")

df.head()

df.shape

df['Category'].value_counts()

plt.figure(figsize=(10,8))
sns.countplot(df['Category'])
plt.show()

df['Category'].unique()

counts = df['Category'].value_counts()
labels = df['Category'].unique()

plt.figure(figsize=(15,10))
plt.pie(counts, labels=labels, autopct='%1.1f%%')
plt.title('Resume Category Distribution')
plt.show()

"""## Exploring Resume"""

df['Resume'][0]

"""# Cleaning Data:

1 URLs,

2 hashtags,

3 mentions,

4 special letters,

5 punctuations:
"""

import re

def cleanResume(txt):
    cleantxt = re.sub('http\S+', ' ', txt)  # Remove URLs
    cleantxt = re.sub('#\S+', ' ', cleantxt)  # Remove hashtags
    cleantxt = re.sub('@\S+', ' ', cleantxt)  # Remove mentions
    cleantxt = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', cleantxt)  # Remove special characters
    cleantxt = re.sub(r'[^\x00-\x7f]', ' ', cleantxt)  # Remove non-ASCII characters
    cleantxt = re.sub('\s+', ' ', cleantxt)  # Replace multiple spaces with a single space
    cleantxt = cleantxt.strip()  # Remove leading/trailing spaces
    return cleantxt

# Test the function
cleaned_text = cleanResume("my #### $ #  #noorsaeed website like is this http://heloword and access it @gmain.com")
print(cleaned_text)

#cleaning every x value or every resume column value using lambda function
df['Resume'] = df['Resume'].apply(lambda x: cleanResume(x))

df['Resume'][3]

"""# Words into Categorical Values"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])
df['Category'].unique()

"""## Vectorisation"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf.fit_transform(df['Resume'])
reqtext = tfidf.transform(df['Resume'])

reqtext

"""## Splitting"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(reqtext, df['Category'], test_size=0.2, random_state=42)

X_train.shape

X_test.shape

"""## Train the model and printing classification report"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier()
clf = OneVsRestClassifier(knn)
clf.fit(X_train, y_train)
ypred = clf.predict(X_test)
print(ypred)

print(accuracy_score(y_test,ypred))

"""## Prediction System"""

import pickle
pickle.dump(tfidf,open('tfidf.pkl','wb'))
pickle.dump(clf, open('clf.pkl', 'wb'))

myresume = """I am a data scientist specializing in machine
learning, deep learning, and computer vision. With
a strong background in mathematics, statistics,
and programming, I am passionate about
uncovering hidden patterns and insights in data.
I have extensive experience in developing
predictive models, implementing deep learning
algorithms, and designing computer vision
systems. My technical skills include proficiency in
Python, Sklearn, TensorFlow, and PyTorch.
What sets me apart is my ability to effectively
communicate complex concepts to diverse
audiences. I excel in translating technical insights
into actionable recommendations that drive
informed decision-making.
If you're looking for a dedicated and versatile data
scientist to collaborate on impactful projects, I am
eager to contribute my expertise. Let's harness the
power of data together to unlock new possibilities
and shape a better future.
Contact & Sources
Email: 611noorsaeed@gmail.com
Phone: 03442826192
Github: https://github.com/611noorsaeed
Linkdin: https://www.linkedin.com/in/noor-saeed654a23263/
Blogs: https://medium.com/@611noorsaeed
Youtube: Artificial Intelligence
ABOUT ME
WORK EXPERIENCE
SKILLES
NOOR SAEED
LANGUAGES
English
Urdu
Hindi
I am a versatile data scientist with expertise in a wide
range of projects, including machine learning,
recommendation systems, deep learning, and computer
vision. Throughout my career, I have successfully
developed and deployed various machine learning models
to solve complex problems and drive data-driven
decision-making
Machine Learnine
Deep Learning
Computer Vision
Recommendation Systems
Data Visualization
Programming Languages (Python, SQL)
Data Preprocessing and Feature Engineering
Model Evaluation and Deployment
Statistical Analysis
Communication and Collaboration
"""

import pickle

# Load the trained classifier
clf = pickle.load(open('clf.pkl', 'rb'))

# Clean the input resume
cleaned_resume = cleanResume(myresume)

# Transform the cleaned resume using the trained TfidfVectorizer
input_features = tfidf.transform([cleaned_resume])

# Make the prediction using the loaded classifier
prediction_id = clf.predict(input_features)[0]

# Map category ID to category name
category_mapping = {
    15: "Java Developer",
    23: "Testing",
    8: "DevOps Engineer",
    20: "Python Developer",
    24: "Web Designing",
    12: "HR",
    13: "Hadoop",
    3: "Blockchain",
    10: "ETL Developer",
    18: "Operations Manager",
    6: "Data Science",
    22: "Sales",
    16: "Mechanical Engineer",
    1: "Arts",
    7: "Database",
    11: "Electrical Engineering",
    14: "Health and fitness",
    19: "PMO",
    4: "Business Analyst",
    9: "DotNet Developer",
    2: "Automation Testing",
    17: "Network Security Engineer",
    21: "SAP Developer",
    5: "Civil Engineer",
    0: "Advocate",
}

category_name = category_mapping.get(prediction_id, "Unknown")

print("Predicted Category:", category_name)
print(prediction_id)